language: c
compiler:
  - gcc

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   -   secure: "iIk5N6U4s0S8e4kQMjr2hAXIGRGXBKQyk1rtq5fQiCA2nijHXw3M+1/OSkTbCh13pk0e8JP+6EXrt5X2qG84C5yPgOyDDn6emq5aTvUR6e/wwAadntYV4JrEGK+PW3ylWlFx7qU6PhEGRyLHgzEZ4chpdaHoa/4fMtt/7g0wiJkAfT863jxHGVTDHoH+Ti9brs7q4ArmKp4pe4RbbonBvvQKrGvf8Equt5jzG6m99ofWrMtp7Dx5RSpwsMuc6NS4J3nWGPw+tkvslspBXCa+zKysO6E846SppUu5qB//j/O8mm3pR9VwANVSI/dyAvW8ZFMi4I41mimQ2G8q2et/Eq8A7MrjhMyXvKNfemdcGeGraiaHDMmoblfleTYEt7bR2KdLw+yjrOLdS7A+G4kfQtkUCk9QfrfmE178aSMrlup+nPA54uzEgvAr9NrjcoSqPYs1mUQ0oNQde8ZI03c5rx8SCVGvD/9ZKRrQn0z3a3PLcd/ZQnpURtVF+q75RDzgBOaHtfkxv0Nh/CS/T/CcNExjLbhHc0G6Cs7tjub83T1blYvezmBNqpQJRYqwfcuL4l7sGwdG+T8HKkddRzM9HNd8JAWJWN/mk2pbKu8ZyQjctGVZia4QIGfP7tTBSXf8M7N7E1GgnfXhK0x3j4M0tmtFiMWHJkiY6UufaEyYegA="
   
addons:
  coverity_scan:
    project:
      name: "liuchao412/CoverityTravisScan"
      description: "Your project description here"
    notification_email: liuchao412@foxmail.com
    build_command: "make -j4"
    branch_pattern: master

    
script:
  - make -j2   
